### ISSUE TITLE
Use of interfaces

### ISSUE THREAD

**Issue by mustafaekim** [edcarroll/ta-json#12]
Does the library support using an interface type within a class? Say my class User has a property "animal" of type Animal, which is an interface? I didnt figure out how I can do that. It seems like I cannot use @JsonType(Animal)

**Comment by edcarroll** [comment]
The issue is that interfaces aren't a thing in Javascript - Typescript is compiled by using type erasure so all interfaces get deleted. Since they don't exist in Javascript, `ta-json` isn't able to use them when casting, as they're no longer there - which is why you need to use classes for everything. Hope that makes sense!

**Comment by mustafaekim** [comment]
Oh ok. Thank you very much.
