### ISSUE TITLE
is extending JSON a good idea?

### ISSUE THREAD

**Issue by mustafaekim** [edcarroll/ta-json#13]
Today I've checked many similar libraries but none of them extends JSON, instead, they offer some new static methods for transformation. Extending JSON does not sound like a good idea, why did you prefer such a way?

**Comment by edcarroll** [comment]
The library doesn't extend `JSON`, in fact to use it you must import a class called JSON like so: `import {JSON} from "ta-json";` - the reason I've done it this way is so that it is a drop in replacement, and the `parse` and `stringify` methods fall back to the global `JSON` object anyway.

If you want to still use the global `JSON` at the same time, you can do `import {JSON as TaJson} from "ta-json";`.

**Comment by mustafaekim** [comment]
Oh, while copy&pasting I didnt even realize that I've imported JSON from ta-json.

importing with a different name as you've recommended made me feel safer, thanks :)
