### ISSUE TITLE
Constructor is not called

### ISSUE THREAD

**Issue by mustafaekim** [edcarroll/ta-json#17]
Hi, it seems like while deserializing, the constructor is never called. Is that the expected behavior? To me, that sounds very odd. The abstract class BaseDoc has a @JsonProperty declared, but the property is not set.

AccountDoc
```ts
import { BaseDoc } from "./base-doc";
import { JsonObject, JsonProperty } from "ta-json";

@JsonObject()
export class AccountDoc extends BaseDoc {

    @JsonProperty() fullName: string;
    @JsonProperty() email: string;
    @JsonProperty() password: string;

    constructor() {
        super("AccountDoc");
    }
}
```

BaseDoc
```ts
import { ObjectID } from "mongodb";
import { JsonProperty } from "ta-json";

export abstract class BaseDoc {

    @JsonProperty() private collectionName: string;
    
    _id: ObjectID;

    constructor(collectionName: string) {
        this.collectionName = collectionName;
    }

    public getId(): string { return this._id.toHexString(); }
    public get_id(): ObjectID { return this._id; }
    public getCollectionName(): string { return this.collectionName; }
    public setCollectionName(value: string) { this.collectionName = value; }
}
```

Test case
```ts
    it('should build AccountDoc class', () => {
        let body = { "fullName": "Mustafa Ekim", "email": "ekim.mustafa@xxx.com", "password": "xxx" };
        let accountDoc: AccountDoc = TA.deserialize<AccountDoc>(body as any, AccountDoc);
        console.dir(accountDoc);
        expect(accountDoc.getCollectionName()).to.equal("AccountDoc");
        expect(accountDoc.fullName).to.be.equal("Mustafa Ekim");
        expect(accountDoc instanceof AccountDoc).to.equal(true);
    });
```

the collectionName property is never set.

AssertionError: expected undefined to equal 'AccountDoc'

**Comment by edcarroll** [comment]
This is the expected behaviour - as it allows you to have a custom constructor that can be called manually in your code (with field initializers and the like) but still use this library when rebuilding classes from JSON.

What you want to do can be achieved by using `@JsonConstructor` and passing `{ runConstructor: true }` as the 3rd argument of `deserialize`.

Account Doc
```typescript
import { BaseDoc } from "./base-doc";
import { JsonObject, JsonProperty } from "ta-json";

@JsonObject()
export class AccountDoc extends BaseDoc {

    @JsonProperty() fullName: string;
    @JsonProperty() email: string;
    @JsonProperty() password: string;

    constructor() {
        // Optional - avoids you having to write "AccountDoc" twice
        this.accountDocCtr();
    }

    @JsonConstructor()
    public accountDocCtr() {
        this.collectionName = "AccountDoc";
    }
}
```

**Comment by mustafaekim** [comment]
Yes, thank you, that worked, however I didn't understand why you do not use the existing constructor but create another method for constructing?

**Comment by mustafaekim** [comment]
I think that, running the constructor should be default, to me, an instance of a class that the constructor is not called, cannot be called an instance of this class.

**Comment by mustafaekim** [comment]
What I mean, to me, constructor should have been called in any case. @JsonConstructor is a nice feature that is better to stay optional like that. Because what you require is to change the design of our classes. That does not sound good

**Comment by edcarroll** [comment]
When I created this library, one of the first major decisions would be whether or not to run the constructor when creating classes.

I decided not to, mainly because running them would require everyone to rewrite their class constructors without any parameters **(so either way changes would have to have been made)**, and with that comes the loss of the ability to have 'useful' constructors. For example:

```typescript
class Person {
    public firstName:string;
    public lastName:string;

    constructor(firstName:string, lastName:string) {
        this.firstName = firstName;
        this.lastName = lastName;
    }
}
```

In the above example, we have a 'useful' constructor, which the programmer can use more fluidly, for example:

```typescript
let ed = new Person("Edward", "Carroll");
````
rather than

```typescript
let ed = new Person();
ed.firstName = "Edward";
ed.lastName = "Carroll";
```

This has other useful benefits - namely that you know that certain properties won't be null once the class has been instantiated. With Typescript's new `strictNullChecks` on you can then assert that `firstName` and `lastName` are never null, which is helpful in itself.

The idea is that whenever you're converting a JSON representation of a class into an instance of said class, it should have already had it's constructor run, and running it again is pointless and may produce odd results.

That said, there are still situations where you might like to set default values - which is where `@JsonConstructor` comes in. However, in order to not duplicate your code, it makes the most sense to add a `defaultValues()` method, which sets them and acts as the `@JsonConstructor`, but is also called from the normal constructor.

Finally, this isn't a new method for creating instances of classes - C# actually does something quite similar, as does Java - it's just not so commonly used 😄 

I hope I've answered your queries sufficiently.

**Comment by mustafaekim** [comment]
I am totally satisfied with your answer, thank you very much. I will try to think that way.
